/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SyncWithCounty;

import org.junit.Test;
import static org.junit.Assert.*;

public class PyTest {
    @Test public void testRun(){
        Sync py = new Sync();
        assertTrue("Returns true", (Boolean) py.run());
    }

}
